apiVersion: v1            # We're creating a Service (part of v1 API group)
kind: Service             # This file is for a Service resource
metadata:
  name: book-api-service  # Name of the service
spec:
  selector:               # Connect this service to pods with the "app: book-api" label
    app: book-api
  ports:                  # Define the ports for the service
    - protocol: TCP       # Use TCP (the usual protocol for web apps)
      port: 80            # Expose the app to users on port 80 (standard HTTP port)
      targetPort: 8000    # Forward traffic to port 8000 inside the pods
  type: LoadBalancer      # Make the service accessible to the internet
