"""Added follow/unfollow system

Revision ID: 589f4ca94967
Revises: c5279fe273c2
Create Date: 2025-01-18 12:44:59.414226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '589f4ca94967'
down_revision: Union[str, None] = 'c5279fe273c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['followed_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], ondelete='CASCADE'),
    sa.UniqueConstraint('follower_id', 'followed_id', name='unique_follower_followed')
    )
    op.add_column('users', sa.Column('followers_count', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('following_count', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'following_count')
    op.drop_column('users', 'followers_count')
    op.drop_table('followers')
    # ### end Alembic commands ###
